image:
  file: .gitpod.Dockerfile
tasks:
  - init: ~/flutter/bin/flutter config --enable-web && ~/flutter/bin/flutter packages get
ports:
  - port: 8080
vscode:
  extensions:
    - Dart-Code.dart-code@3.7.0-test.gitpod-debug:e2joCoZdkG/bKPaZwBPEXA==
    - Dart-Code.flutter@3.6.0:bAElIiRvpBSK2AT2+PDj0w==
