image:
  file: .gitpod.Dockerfile
tasks:
  - init: flutter config --enable-web && flutter packages get
ports:
  - port: 8080
vscode:
  extensions:
    - Dart-Code.dart-code@3.6.0:OIKJQXmfWHoIMVCiWrcLsQ==
    - Dart-Code.flutter@3.6.0:bAElIiRvpBSK2AT2+PDj0w==
